name: golangci-lint
on:
  - push

permissions:
  contents: read

jobs:
  hello-action:
    runs-on: ubuntu-latest:docker://docker.gitea.com/runner-images:ubuntu-latest
    steps:
      - run: echo "Trigger ${{ github.event_name }}

